### ISSUE TITLE
Query regarding riscv_vector headerfile

### ISSUE THREAD

**Issue by soniab** [riscv/rvv-intrinsic-doc#23]
I am trying to run example programs but did not get "riscv_vector.h" header file. 

I have already installed riscv-gnu-toolchain along with riscv-pk and riscv-spike.

Do I need to install some other tools or some other environment to access riscv vector extension intrinsics (riscv_vector.h) ?

**Comment by jim-wilson** [comment]
We haven't released a compiler with vector support yet.  So all you can do is assembly level programming at the moment.
