### ISSUE TITLE
How to define vzero and vreinterpret

### ISSUE THREAD

**Issue by WilliamWangPeng** [riscv/rvv-intrinsic-doc#33]
Dear all,    
&ensp; &ensp;&ensp; We are adding new intrinsics which is depending on riscv-v-spec 0.9 recently,  but there remain two new intrinsics "vzero and vreinterpret" which I have never seen in riscv-v-spec 0.9.      
&ensp; &ensp;&ensp; The definition of vzero and  vreinterpret we have defined is as following in 
 src/llvm/include/llvm/IR/IntrinsicsRISCVVector.td
```  
def int_riscv_vzero_i8m1
  : Intrinsic<[llvm_nxv1i8_ty],
              [],
              [IntrNoMem]>;  


def int_riscv_vreinterpret_u64_i64_u64m2
  : Intrinsic<[llvm_nxv2i64_ty],
              [llvm_nxv2i64_ty],
              [IntrNoMem]>;
```
&ensp; &ensp;&ensp; But in src/llvm/include/llvm/IR/RISCVInstrInfoV.td,  the riscv-v-spec 0.9 doesn't give any illustration of the encoding definition to vzero and  vreinterpret, Do you know how to define them?    
```  
//__builtin_riscv_vzero_i8m1()
def : Pat<(int_riscv_vzero_i8m1), ()>;

//___builtin_riscv_vreinterpret_u64_i64_u64m2(src)
def : Pat<(int_riscv_vreinterpret_u64_i64_u64m2), ()>;
```     

One example is as following, vzero and vreinterpret don't have the encoding definition.  
```
let hasSideEffects = 0, mayLoad = 1, mayStore = 0 in
multiclass VLoad_UnitStride<bits<3> nf, bits<1> mew, bits<2> mop,
                            bits<3> width, string opcodestr> {
  def _m  : RVInstVLoad<nf, mew, mop, width, RVV_Masked, OPC_LOAD_FP,
                  (outs VR:$vd), (ins GPR:$rs1, Zero:$zero, VMR:$vm),
                  opcodestr, "$vd, ${zero}(${rs1}), $vm"> {
    let Inst{24-20} = 0b00000;
  }
  def _um : RVInstVLoad<nf, mew, mop, width, RVV_Unmasked, OPC_LOAD_FP,
                  (outs VR:$vd), (ins GPR:$rs1, Zero:$zero),
                  opcodestr, "$vd, ${zero}(${rs1})"> {
    let Inst{24-20} = 0b00000;
  }
}  

defm VLE8_V : VLoad_UnitStride<0b000, 0b0, 0b00, 0b000, "vle8.v">, Sched<[]>;
defm VLE16_V : VLoad_UnitStride<0b000, 0b0, 0b00, 0b101, "vle16.v">, Sched<[]>;  

//__builtin_riscv_vle8_v_i8m1(base)
def : Pat<(int_riscv_vle8_v_i8m1 GPR:$rs1), (VLE8_V_um GPR:$rs1, 0)>;

//__builtin_riscv_vle16_v_i16m1(base)
def : Pat<(int_riscv_vle16_v_i16m1 GPR:$rs1), (VLE16_V_um GPR:$rs1, 0)>;

```

Thank you  
Best Regards  
William

**Comment by rdolbeau** [comment]
Those intrinsics don't correspond to an actual instruction. They are here to help with writing high-level code.

`̀vzero` outputs an all-zero vector (of the appropriate type), i.e. __builtin_riscv_vzero_i8m1() outputs a zero-valued `vint8m1_t`. The compiler has some freedom on how to achieve that (using a zero-generating idiom like `xor a,a,a`, reusing a previously-known-to-be-zero vector, etc.)

`vreinterpret` like ___builtin_riscv_vreinterpret_i64_u64m2 merely changes the high-level types without changing any bit in the vector. In this case it merely changes the 'signedness' of the type, reinterpreting `vint64m2_t` to `vuint64m2_t`. 

Both are described as 'utilisy functions' in https://github.com/riscv/rvv-intrinsic-doc/blob/master/rvv-intrinsic-rfc.md#utility-functions

**Comment by WilliamWangPeng** [comment]
> Those intrinsics don't correspond to an actual instruction. They are here to help with writing high-level code.
> 
> `̀vzero` outputs an all-zero vector (of the appropriate type), i.e. __builtin_riscv_vzero_i8m1() outputs a zero-valued `vint8m1_t`. The compiler has some freedom on how to achieve that (using a zero-generating idiom like `xor a,a,a`, reusing a previously-known-to-be-zero vector, etc.)
> 
> `vreinterpret` like ___builtin_riscv_vreinterpret_i64_u64m2 merely changes the high-level types without changing any bit in the vector. In this case it merely changes the 'signedness' of the type, reinterpreting `vint64m2_t` to `vuint64m2_t`.
> 
> Both are described as 'utilisy functions' in https://github.com/riscv/rvv-intrinsic-doc/blob/master/rvv-intrinsic-rfc.md#utility-functions

Thank you for your reply, dear Romain Dolbeau
I have known the use of vzero and vreinterpret, so due to all of these definition, we don't need to define the vzero and vreinterpret pat in src/llvm/include/llvm/IR/RISCVInstrInfoV.td like int_riscv_vle8_v_i8m1, right?
```  
//__builtin_riscv_vzero_i8m1()
def : Pat<(int_riscv_vzero_i8m1), ()>;

//___builtin_riscv_vreinterpret_u64_i64_u64m2(src)
def : Pat<(int_riscv_vreinterpret_u64_i64_u64m2), ()>;  
```
