### ISSUE TITLE
Expanding for float type

### ISSUE THREAD

**Issue by joy2myself** [riscv/rvv-intrinsic-doc#34]
Hi,
I find that there are no intrinsics such as `vreinterpret_v_f16m1_f32m1(vfloat16m1_t src)`.
How can I expand float types for example from `vfloat16m1_t` to `vfloat32m1_t`?

**Comment by kito-cheng** [comment]
reinterpret intrinsic is for bit-wise casting, like reinterpret_cast in C++, so reinterpret two fp16 to fp32 is meaningless in general, in case that's what you want you can reinterpret to uint16 and than reinterpret to fp32.

But according your issue title, I guess you are finding vfwcvt_f_f_v_* ?

**Comment by joy2myself** [comment]
Thanks a lot Kito. That's what I want.
