### ISSUE TITLE
Explicitly VL API for mask operation should have _vl suffix and vl operand

### ISSUE THREAD

**Issue by kito-cheng** [riscv/rvv-intrinsic-doc#49]
Those instructions are use `VL` in their instruction definition[1], so I think we should add vl to the parameter list of  those functions, e.g `vbool1_t vmand_mm_b1 (vbool1_t op1, vbool1_t op2);` should be `vbool1_t vmand_mm_b1_vl (vbool1_t op1, vbool1_t op2, size_t vl);`

[1] https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#16-vector-mask-instructions

**Comment by zakk0610** [comment]
Thanks for report this bug!!
