### ISSUE TITLE
Passing vl as arguments of intrinsics

### ISSUE THREAD

**Issue by Hsiangkai** [riscv/rvv-intrinsic-doc#8]
We provide intrinsics with/without vl at the same time.

vop_vv_type(a, b)
vop_vv_type_vl(a, b, gvl)

**Comment by rdolbeau** [comment]
Hello,
It seems to me we are in somewhat of an agreement here - having both versions of the intrinsics, with the VL-explicit version (with an integer or integer-like parameter from #20) being essentially a shortcut for adding an explicit vsetvl() before the instruction (i.e., the intrinsics might compute on fewer elements if the requested VL is too big and/or somehow illegitimate, user beware). And as 0 is a legitimate value for VL, 0 is not a special case.
So - maybe we can close this one as well to move things forward with the proposal?
Cordially,

**Comment by Hsiangkai** [comment]
Agree. In current stage, we keep both versions of intrinsics as described in the RFC.
