### ISSUE TITLE
Intrinsic functions supported are inconsistent on different HW config

### ISSUE THREAD

**Issue by zakk0610** [riscv/rvv-intrinsic-doc#9]
For example:
`vslide1up/down` and `vmv.s.x` have below constraints:
If `XLEN` < `SEW`: the value is `sign-extended` to SEW bits.
If `XLEN` > `SEW`: the least-significant bits are copied over and the high SEW-XLEN bits are ignored.

Current SiFive proposal: 
provide signed/unsigned interface, but the second operand type always is long. (The second operand type is corresponding to `XLEN`) 

In RV64 with `SEW`=64 config (`XLEN` == `SEW`):
`vuint64m1_t vslide1up_vs_u64m1 (vuint64m1_t src, long value);` // Is it weird? In this HW config, the value's type can be unsigned long

In RV32 with `SEW`=64 config (`XLEN` < `SEW`): 
`vuint64m1_t vslide1up_vs_u64m1(vuint64m1_t src, long value);` // unsigned long value is illegal because value would be `sign-extended` to 64 bits.

Does it also mean all vector-scalar integer operations, almost the type of scalar should be long or unsigned long?
In addition, `FLEN` < `SEW` has similar problem.

There is another problem(?) in RV64 `SEW`=32 config (`XLEN` > `SEW`)
`vint32m1_t  vslide1up_vs_i32m1 (vint32m1_t src, long value);` // The value will be truncated to 32-bit implicitly

one of solution is support intrinsic function optionally on different HW config.
For example, on RV32 platform, `SEW`=64 vector-scalar integer operations would not supported.

Any idea or suggestion?

ps. `vslide1up/down`: The slide instructions move one elements up and down a vector register group.
ps. `vmv.s.x`: The integer scalar move instruction copies the scalar integer register to element 0 of the destination vector register.
ps. spec define the value in SEW up to max(XLEN,FLEN).
ps. RV32 means `XLEN` and long is 32 bit
ps. in intrinsic document, `vmv.s.x` api had not fixed yet.

**Comment by jinma-work** [comment]
hi ，
I try to process the function ```vmv_x_s_i64m1_i64``` on rv32 in gcc, and when my return value is ```int64_t ``` (low 32 bits are stored in register ```a0``` and high 32 bits are stored in register ```a1```), since the actual return value is stored in a 32-bit register(```a0```), how should the high 32 bits of int64_t(```a1```) be handled? I think a signed extension process from ```int32_t``` to ```int64_t ``` may be needed. Or simply ignore the upper 32 bits(```a1```), but this will cause some unknown data to be generated, resulting in wrong results.

This is my function:
```
int64_t vmvxsi64m1_s_nomask_builtin_test (int64_t *x, size_t vl)
{
    vint64m1_t vx;
    vx = vle64_v_i64m1 (x, vl);
    return  vmv_x_s_i64m1_i64 (vx);
}
```

**Comment by topperc** [comment]
In LLVM, vmv_x_s_i64m1_i64 reads bits 63:0 of the vector register into two GPRs. For the return from vmvxsi64m1_s_nomask_builtin_test bits 31:0 will put in a0, and bits 63:32 will be put in a1. The intent is to make rv32 vs rv64 invisible to the C programmer.

~Craig
