### ISSUE TITLE
naming of vmerge_vvm_f16mf4

### ISSUE THREAD

**Issue by pshung** [riscv/rvv-intrinsic-doc#90]
I think vmerge_vvm_f16mf4 violates the naming rule of RVV spec.
Would it be better to call vfmerge_vvm_f16mf4?

**Comment by zakk0610** [comment]
https://github.com/riscv/rvv-intrinsic-doc/blob/master/rvv-intrinsic-rfc.md#naming-rules
The intrinsic names are as close as the assembly mnemonics, and `vmerge_vvm_f16mf4 ` would generates `vmerge.vvm` instruction.
so it's why the name is `vmerge_vvm_f16mf4.`
Hope is make sense to you.
