### ISSUE TITLE
Unify the abbreviation of destination.

### ISSUE THREAD

**Issue by pshung** [riscv/rvv-intrinsic-doc#91]
The document uses both the 'dst' and 'dest' as the abbreviation of destination.

vint8m1_t vredsum (vint8m1_t dst, vint8mf8_t vector, vint8m1_t scalar, size_t vl);
vint8mf8_t vcompress (vbool64_t mask, vint8mf8_t dest, vint8mf8_t src, size_t vl);

Could we unify the naming?  "dest"

**Comment by zakk0610** [comment]
Good catch, thanks!!
