### ISSUE TITLE
overloaded vlm

### ISSUE THREAD

**Issue by kuanlinchentw** [riscv/rvv-intrinsic-doc#93]
Hi,

In [Vector Mask Load/Store Functions](https://github.com/riscv/rvv-intrinsic-doc/blob/master/overloaded_intrinsic_funcs/10_vector_mask_functions.md#vector-mask-loadstore-functions), I think "vlm" cannot be overloaded, because their arguments are all the same.
if I misunderstood please let me know, thanks.

**Comment by zakk0610** [comment]
Good catch, thanks!!!
